{
    "name": "DCT Security Operations",
    "summary": "Connected guard, coverage, attendance and security service operations",
    "version": "19.0.1.0.0",
    "category": "Services/Security",
    "author": "Digital Creativity Technologies",
    "license": "AGPL-3",
    "depends": ["web", "mail", "hr", "hr_attendance", "hr_holidays", "account"],
    "data": [
        "security/groups.xml",
        "security/ir.model.access.csv",
        "security/rules.xml",
        "data/security_data.xml",
        "views/foundation_views.xml",
        "views/contract_views.xml",
        "views/planning_views.xml",
        "views/attendance_views.xml",
        "views/operations_views.xml",
        "views/finance_views.xml",
        "views/dashboard_views.xml",
        "report/security_reports.xml",
        "views/menus.xml",
        "views/policy_views.xml",
    ],
    "demo": ["demo/security_demo.xml"],
    "assets": {
        "web.assets_backend": [
            "dct_security_management/static/lib/leaflet/leaflet.js",
            "dct_security_management/static/lib/leaflet/leaflet.css",
            "dct_security_management/static/src/operations.js",
            "dct_security_management/static/src/operations.xml",
            "dct_security_management/static/src/operations.scss",
        ],
        "web.assets_tests": ["dct_security_management/static/tests/operations_tour.js"],
    },
    "application": True,
    "installable": True,
}
