{
    "name": "DCT Accounting",
    "summary": "Native Odoo accounting workspace with interactive Community reports",
    "version": "19.0.2.5.0",
    "category": "Accounting/Accounting",
    "author": "Digital Creativity Technologies",
    "license": "AGPL-3",
    "depends": [
        "account",
        "web",
        "web_responsive",
        "web_dark_mode",
        "web_dialog_size",
        "account_financial_report",
        "account_tax_balance",
        "partner_statement",
        "account_asset_management",
        "account_chart_update",
        "account_journal_lock_date",
        "account_lock_date_update",
        "account_move_post_date_user",
        "account_move_template",
        "account_usability",
        "account_reconcile_oca",
        "account_statement_import_camt",
        "account_statement_import_file_reconcile_oca",
        "account_statement_import_online",
        "account_statement_import_qif",
        "account_statement_import_sheet_file_xlsx",
        "mis_builder_budget",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/account_report_views.xml",
        "report/financial_report_templates.xml",
        "views/accounting_dashboard_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "dct_accounting/static/src/theme/theme.js",
            "dct_accounting/static/src/accounting_dashboard/accounting_dashboard.js",
            "dct_accounting/static/src/accounting_dashboard/accounting_dashboard.xml",
            "dct_accounting/static/src/accounting_dashboard/accounting_dashboard.scss",
            "dct_accounting/static/src/journal_dashboard/**/*",
            "dct_accounting/static/src/report/**/*",
            "dct_accounting/static/src/reconcile/reconcile.xml",
            "dct_accounting/static/src/reconcile/reconcile.scss",
        ],
    },
    "application": True,
    "installable": True,
}



